[features]
seeds = false
skip-lint = false
[programs.localnet]
solana_nft_anchor = "9TEtkW972r8AVyRmQzgyMz8GpG7WJxJ2ZUVZnjFNJgWM"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/jimii/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
