[features]
seeds = false
skip-lint = false
[programs.localnet]
solana_nft_anchor = "29Zvg7ACK6DHG9qEHKQadP16QCxugn6UD2nDo77Dewgn"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/jimii/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
